version = 0.2
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SmartDogHouse"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qjsfwefwqn11"
s3_prefix = "SmartDogHouse"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"SmartDogHouse_Websock_conn\" NotificationsTopic=\"Notifications\" ESPspecificTopic=\"ESP\""
