version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SmartDogHouse"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qjsfwefwqn11"
s3_prefix = "SmartDogHouse"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
