AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SmartDogHouse-Serverless
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize : 256


# More info about API Event Sources: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
# More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
Resources:  
  SetConsRangesBySize:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambda/
      Policies:
      - AmazonDynamoDBFullAccess
      Handler: app.setConsRangesBySize
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello7
            Method: get

  SetConsRangesByDog:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: lambda/
        Policies:
        - AmazonDynamoDBFullAccess
        Handler: app.setConsRangesByDog
        Runtime: nodejs14.x
        Events:
          HelloWorld:
            Type: Api 
            Properties:
              Path: /hello8
              Method: get
  SetFoodScheduleBySize:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambda/
      Policies:
      - AmazonDynamoDBFullAccess
      Handler: app.setFoodScheduleBySize
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello5
            Method: get
  SetFoodScheduleByDog:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambda/
      Policies:
      - AmazonDynamoDBFullAccess
      Handler: app.setFoodScheduleByDog
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello6
            Method: get
  GetWaterConsumptionByDog:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambda/
      Policies:
      - AmazonDynamoDBFullAccess
      Handler: app.getWaterConsumptionByDog
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get
  GetFoodConsumptionByDog:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambda/
      Policies:
      - AmazonDynamoDBFullAccess
      Handler: app.getFoodConsumptionByDog
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello1
            Method: get
  WaterConsumptionAlarm:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambda/
      Policies:
      - AmazonDynamoDBFullAccess
      Handler: app.waterConsumptionAlarm
      Runtime: nodejs14.x
  FoodConsumptionAlarm:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: lambda/
        Policies:
        - AmazonDynamoDBFullAccess
        Handler: app.foodConsumptionAlarm
        Runtime: nodejs14.x


#Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  GetWaterConsumptionByDogApi:
#    Description: "API Gateway endpoint URL for Prod stage for GetWaterConsumptionByDog function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#  GetWaterConsumptionByDogFunction:
#    Description: "GetWaterConsumptionByDog Lambda Function ARN"
#    Value: !GetAtt GetWaterConsumptionByDog.Arn
# GetWaterConsumptionByDogIamRole:
#   Description: "Implicit IAM Role created for GetWaterConsumptionByDog"
#   Value: !GetAtt GetWaterConsumptionByDogRole.Arn
